apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-sample
  namespace: kubesphere-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webhook-sample
  template:
    metadata:
      labels:
        name: webhook-sample
    spec:
      containers:
        - name: webhook
          image: leiwanjun/webhook-sample:latest
          command:
            - webhook-sample
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
          lifecycle:
            preStop:
              httpGet:
                path: /preStop
                port: 8080
                scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 50Mi
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-sample
  namespace: kubesphere-monitoring-system
spec:
  selector:
    name: webhook-sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
